const makeSquizImageBaseUrl = 'https://s3.ap-northeast-2.amazonaws.com/hmk.assets/make_squiz'

export const malePhotos = [
    `${makeSquizImageBaseUrl}/male/male1.avif`,
    `${makeSquizImageBaseUrl}/male/male10.webp`,
    `${makeSquizImageBaseUrl}/male/male11.jpeg`,
    `${makeSquizImageBaseUrl}/male/male12.webp`,
    `${makeSquizImageBaseUrl}/male/male14.webp`,
    `${makeSquizImageBaseUrl}/male/male15.webp`,
    `${makeSquizImageBaseUrl}/male/male16.webp`,
    `${makeSquizImageBaseUrl}/male/male17.jpeg`,
    `${makeSquizImageBaseUrl}/male/male18.jpeg`,
    `${makeSquizImageBaseUrl}/male/male2.avif`,
    `${makeSquizImageBaseUrl}/male/male20.jpeg`,
    `${makeSquizImageBaseUrl}/male/male22.jpeg`,
    `${makeSquizImageBaseUrl}/male/male3.avif`,
    `${makeSquizImageBaseUrl}/male/male3.webp`,
    `${makeSquizImageBaseUrl}/male/male4.webp`,
    `${makeSquizImageBaseUrl}/male/male5.webp`,
    `${makeSquizImageBaseUrl}/male/male6.png`,
    `${makeSquizImageBaseUrl}/male/male7.webp`,
    `${makeSquizImageBaseUrl}/male/male9.webp`,
    `${makeSquizImageBaseUrl}/male/mele8.webp`,
];


export const femalePhotos = [
    `${makeSquizImageBaseUrl}/female/female.avif`,
    `${makeSquizImageBaseUrl}/female/female1.avif`,
    `${makeSquizImageBaseUrl}/female/female10.jpg`,
    `${makeSquizImageBaseUrl}/female/female11.jpg`,
    `${makeSquizImageBaseUrl}/female/female12.jpg`,
    `${makeSquizImageBaseUrl}/female/female13.jpg`,
    `${makeSquizImageBaseUrl}/female/female14.jpg`,
    `${makeSquizImageBaseUrl}/female/female16.jpg`,
    `${makeSquizImageBaseUrl}/female/female17.jpg`,
    `${makeSquizImageBaseUrl}/female/female19.jpg`,
    `${makeSquizImageBaseUrl}/female/female20.jpg`,
    `${makeSquizImageBaseUrl}/female/female3.jpg`,
    `${makeSquizImageBaseUrl}/female/female5.webp`,
    `${makeSquizImageBaseUrl}/female/female6.jpeg`,
    `${makeSquizImageBaseUrl}/female/female7.jpg`,
    `${makeSquizImageBaseUrl}/female/female8.jpg`,
    `${makeSquizImageBaseUrl}/female/female9.jpg`,
];